variables:
  DEPLOY: "false"
  NATIVE: "false"
  SAMO_MAVEN_DOCKER_RELEASE_REGISTRY: docker.io

include:
  - project: '1000kit/infra/config/gitlab-ci-quarkus-template'
    ref: 'v3-release'
    file: '.gitlab-ci-release.yml'

