apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}-deployment
  labels:
    app: {{ .Values.app_name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
