{{- if .Values.openshift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-external-route
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
annotations:
spec:
  host: {{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.domain.external.default_url }}
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}