kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-vault-secret
  annotations:
    avp.kubernetes.io/path: "secret/webapp/config"  
type: Opaque
stringData:
  password: <password>
  username: <username>
