name: Build

on:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'
      - '[0-9]+.x'
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    uses: onecx/ci-quarkus/.github/workflows/build.yml@v1
    secrets: inherit
    with:
      native: true
      nativeMulti: true


