name: Build Feature Branch

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!fix/[0-9]+.[0-9]+.x'

jobs:
  code-ql:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-codeql.yml@v1
    secrets: inherit
  quarkus:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-build.yml@v1
    secrets: inherit
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    needs: quarkus
    secrets: inherit
