name: Build Pull Request

on:
  pull_request:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'
  pull_request_target:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'

jobs:
  quarkus:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-pr.yml@v1
    secrets: inherit
  sonar:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-sonar.yml@v1
    needs: quarkus
    secrets: inherit
  helm:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    needs: sonar
    secrets: inherit
    with:
      push: false