name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'fix/[0-9]+.[0-9]+.x'

jobs:
  build:
    uses: onecx/ci-quarkus/.github/workflows/build.yml@v1trivy
    secrets: inherit
    with:
      native: false
  trivy-test:
    name: docker trivy scan manual
    # runs-on: [ self-hosted, aws ]
    runs-on: ubuntu-latest
    env:
      TRIVY_DEPENDENCY_TREE: 'true'
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/onecx/ping-quarkus:0.25.0-rc.61'
          severity: 'HIGH,CRITICAL'
          format: table


