name: Build and release application

on:
  push:
    branches:
      - main

jobs:
  quarkus:
    uses: onecx/ci-java/.github/workflows/quarkus.yml@main
  docker:
    uses: onecx/ci-java/.github/workflows/docker.yml@main