name: Trivy scan

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  pr:
    uses: onecx/ci-quarkus/.github/workflows/quarkus-trivy.yml@v1trivy
    secrets: inherit
    with:
      native: false